### ISSUE TITLE
Support for PHP 8.2

### ISSUE THREAD

**Issue by leonhelmus** [baldwin-agency/magento2-module-url-data-integrity-checker#40]
Hey @hostep!

I see that you already created a branch to support php 8.2 :). When do you expect you will supply a stable tag?

**Comment by hostep** [comment]
Thanks for the reminder, I was planning to do it one of the coming days, but found a few minutes today to do it.
See https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/releases/tag/v1.5.1

Enjoy! 🙂

**Comment by leonhelmus** [comment]
@hostep Super!
