### ISSUE TITLE
Regarding, product url path..

### ISSUE THREAD

**Issue by hgati** [baldwin-agency/magento2-module-url-data-integrity-checker#43]
Hi, Thank you for the useful extension.

![](https://gcdnb.pbrd.co/images/as5YvVYh1to2.png)

The entire product line has been reported to have issues. What could be the problem?

It doesn't seem like there is a specific problematic URL.
![](https://gcdnb.pbrd.co/images/lBYkv7TvHWls.png)

**Comment by hostep** [comment]
Hi @hgati

Be aware that `url_path` and `url_key` product attributes are something different.
See [here](https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/issues/25#issuecomment-844369215) and [here](https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/issues/39#issuecomment-1243507549) where we've already explained before why `url_path`'s for products (not for categories!) are bad.
