### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by peterjaap** [baldwin-agency/magento2-module-url-data-integrity-checker#5]
@hostep could you create a new release? There have been 20 commits since 1.0.0 :)

**Comment by hostep** [comment]
Hi @peterjaap 

There are no changes yet to the functionality inside the module, most changes had to do with updating the [phpstan](https://github.com/phpstan/phpstan/) static analyser and to fix some of the new errors it discovered.

Changes: https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/compare/v1.0.0...v1-develop

In my opinion, it doesn't make much sense to release a new version if only code cleanup was done and no functional changes were added.

What do you think?

**Comment by peterjaap** [comment]
@hostep yes you're right, I didn't notice those 20 commits only contain supporting code :)
